### ISSUE TITLE
Choose artifacts versions for assembly

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/bigtop#3]
## Requirements
- Artifacts versions must be `LTS` and `stable`
- Long-term support version must be supported min 2 years
- Artifacts versions must work correctly with each other
- Spark must be min 3.2.3 version

## Tasks
- [x] Choose versions for Hadoop (HDFS, YARN), Zookeeper, Hive and Spark
- [x] Explain why these versions were chosen

**Comment by ya6lis** [comment]
## Versions
- Hadoop - 3.3.5
- YARN - 3.3.5
- Zookeeper - 3.5.9
- Hive - 3.1.3
- Spark - 3.4.2

## Explanation
- Hadoop - The last stable version 
- YARN - Version bundled with Hadoop
- Zookeeper - According to the .bom file, there may be some errors when changing the version because it contains 3 dependencies
- Hive - The last stable version that working with 3.x.y Hadoop ([releases](https://hive.apache.org/general/downloads/))
- Spark - Added a bunch of features and fixes from 3.2.4 like 
     - Releases include enhancements to ANSI compliance and the implementation of new built-in functions to simplify 
     migration from traditional data warehouses.
     - Implement support for DEFAULT values for columns in tables 
     - Support TIMESTAMP WITHOUT TIMEZONE data type

**Comment by Nazarii-Melnyk** [comment]
@ya6lis Коли закриваєш карточку не потрібно її переводити в статус "Done", тільки внизу кнопку "Close issue" (там ще можна вибрати "Close as not planned", це чисто коли якась карточка не потрібна і щоб її не видаляти). Коли таким чином закриєш то гітхаб сам поставить карточці статус "Done"
